import "@shared/template/icons/font/cartzillaIcons.css"
import "@shared/template/styles/theme.scss"
import "@shared/style/global.css"
import "@shared/style/correct.css"
import { AppLayoutProp } from "@/types/propsPage"
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import ModalProvider from "@/shared/context/Modal/provider/ModalProvider"
import { GlobalProvider } from "@/shared/context/Global/GlobalProvider"
import { ToastProvider } from "@/shared/context/Toast/ToastProvider"
import { AuthProvider } from "@/shared/context/Auth"
import { NextIntlClientProvider } from "next-intl"
import { FooterWidget, HeaderWidget, OffAuthWidget } from "@/widgets"
import { ProgressProvider } from "@/shared/context/progress-context"
import { CommonComponentChildren } from "@/types"
import "@shared/style/fonts.css"
 
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

const cartzillaIcons = localFont({
  src: '../shared/template/icons/font/cartzillaIcons.woff2',
  preload: true,
  adjustFontFallback: false,
})

export default function RootLayout({children}:CommonComponentChildren) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Prata&display=swap" rel="stylesheet"/>
            </head>
            <body className={`${inter.className}`}>
                <NextIntlClientProvider>
                <ModalProvider>
                    <GlobalProvider> 
                        <ToastProvider>
                            <AuthProvider authDef={null}> 
                                <ThemeProvider attribute="data-bs-theme" defaultTheme="system" disableTransitionOnChange>
                                    <ProgressProvider> 
                                    <OffAuthWidget/>
                                    <HeaderWidget/>
                                    {children}
                                    <FooterWidget/>
                                    </ProgressProvider>
                                </ThemeProvider>
                            </AuthProvider>
                        </ToastProvider>
                    </GlobalProvider>
                </ModalProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
