import "@shared/template/icons/font/cartzillaIcons.css"
import "@shared/template/styles/theme.scss"
import { AppLayoutProp } from "@/types/propsPage"
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import ModalProvider from "@/shared/context/Modal/provider/ModalProvider"
import { GlobalProvider } from "@/shared/context/Global/GlobalProvider"
import { ToastProvider } from "@/shared/context/Toast/ToastProvider"
import { AuthProvider } from "@/shared/context/Auth"
import { NextIntlClientProvider } from "next-intl"
import { OffAuth } from "@/features/auth"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

const cartzillaIcons = localFont({
  src: '../shared/template/icons/font/cartzillaIcons.woff2',
  preload: true,
  adjustFontFallback: false,
})

export default function RootLayout({children}:AppLayoutProp) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className}`}>
                <NextIntlClientProvider>
                <ModalProvider>
                    <GlobalProvider> 
                        <ToastProvider>
                            <AuthProvider authDef={null}> 
                                <ThemeProvider attribute="data-bs-theme" defaultTheme="light" disableTransitionOnChange>
                                    <OffAuth/>
                                    {children}
                                </ThemeProvider>
                            </AuthProvider>
                        </ToastProvider>
                    </GlobalProvider>
                </ModalProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
