import "@shared/template/icons/font/cartzillaIcons.css"
import "@shared/template/styles/theme.scss"
import "@shared/style/global.css"
import "@shared/style/correct.css"
import "@shared/style/fonts.css"
import "croppie/croppie.css"; 
import 'choices.js/public/assets/styles/choices.css'
import 'primereact/resources/themes/lara-light-blue/theme.css'; // тема (будь-яку)
import "@shared/style/primereact.css"
import 'primereact/resources/primereact.min.css';               // базові стилі
import 'react-datepicker/dist/react-datepicker.css';
import "react-quill-new/dist/quill.snow.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import 'glightbox/dist/css/glightbox.min.css'
 import "@features/hero/biography/show/style/biography.css";

import localFont from 'next/font/local' 
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import ModalProvider from "@/shared/context/Modal/provider/ModalProvider"
import { GlobalProvider } from "@/shared/context/Global/GlobalProvider"
import { ToastProvider } from "@/shared/context/Toast/ToastProvider"
import { AuthProvider } from "@/shared/context/Auth"
import { NextIntlClientProvider } from "next-intl"
import { FooterWidget, HeaderWidget, OffAuthWidget } from "@/widgets"
import { ProgressProvider } from "@/shared/context/progress-context"
import { CommonComponentChildren } from "@/types"
import ReCaptcha from "@/shared/context/reCaptcha/ReCaptcha"
 
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

const cartzillaIcons = localFont({
  src: '../shared/template/icons/font/cartzillaIcons.woff2',
  preload: true,
  adjustFontFallback: false,
})

export default function RootLayout({children}:CommonComponentChildren) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Prata&display=swap" rel="stylesheet"/>
            </head>
            <body className={`${inter.className}`}>
                <NextIntlClientProvider>
                <ModalProvider>
                    <GlobalProvider> 
                        <ToastProvider>
                            <AuthProvider authDef={null}> 
                                <ReCaptcha>
                                <ThemeProvider attribute="data-bs-theme" defaultTheme="system" disableTransitionOnChange>
                                    <ProgressProvider> 
                                    <OffAuthWidget/>
                                    <HeaderWidget/>
                                    {children}
                                    <FooterWidget/>
                                    </ProgressProvider>
                                </ThemeProvider>
                                </ReCaptcha>
                            </AuthProvider>
                        </ToastProvider>
                    </GlobalProvider>
                </ModalProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
