export { default as HomePage } from "./home/ui/HomePage";
export { default as HeroesPage } from "./heroes/ui/HeroesPage";
export { default as HeroAboutPage } from "./hero/about/ui/HeroAboutPage";
export { default as HeroBiograohyPage } from "./hero/boigraphy/ui/HeroBiographyPage";
export { default as HeroPhotoPage } from "./hero/photo/ui/HeroPhotoPage";
export { default as HeroPhotoSetMainPage } from "./hero/photo/ui/HeroPhotoSetMainPage"
export { default as HeroVideoPage } from "./hero/video/ui/HeroVideoPage";
export { default as HeroAudioPage } from "./hero/audio/ui/HeroAudioPage";
export { default as NewHeroPage } from "./newHero/ui/NewHeroPage"